import turtle

window = turtle.Screen()
my_turtle = turtle.Turtle()
my_turtle.color("purple")

my_turtle.forward(50)
my_turtle.left(90)
my_turtle.forward(50)
my_turtle.left(90)
my_turtle.forward(50)
my_turtle.left(90)
my_turtle.forward(50)
my_turtle.right(90)
my_turtle.up()
my_turtle.color("red")
my_turtle.forward(50)
my_turtle.down()
my_turtle.forward(50)
my_turtle.right(90)
my_turtle.forward(50)
my_turtle.right(90)
my_turtle.forward(50)
my_turtle.right(90)
my_turtle.forward(50)
my_turtle.right(90)
window.exitonclick()